name: Deploy Site

on:
  push:
    branches:
      - main # or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Download Warlus binary
        run: |
          curl -L -o walrus https://storage.googleapis.com/mysten-walrus-binaries/walrus-testnet-latest-ubuntu-x86_64
          mv walrus /usr/local/bin/
          chmod +x /usr/local/bin/walrus

      - name: Generate Warlus wallet
        run: |
          walrus generate-sui-wallet

      - name: Download Site-builder binary
        run: |
          curl -L -o site-builder https://storage.googleapis.com/mysten-walrus-binaries/site-builder-testnet-latest-ubuntu-x86_64
          mv site-builder /usr/local/bin/
          chmod +x /usr/local/bin/site-builder

      - name: Install dependencies
        working-directory: ./site
        run: |
          pnpm install

      - name: Build site
        working-directory: ./site
        run: |
          pnpm run build

      - name: Deploy site
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        working-directory: ./site
        run: |
          ls -la
          site-builder --config ./sites-config.yaml publish --epochs 180 ./dist/.
